server:
  port: 8082
  max-http-request-header-size: 32KB

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:

        # User Service
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**,/api/users/**

        # Stadium Service
        - id: stadium-service
          uri: lb://stadium-service
          predicates:
            - Path=/api/fields,/api/fields/**

        # Booking Service is not registered with Eureka.
        - id: booking-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/bookings,/api/bookings/**

        # Payment Service runs directly on port 8086 and is not registered with Eureka.
        - id: payment-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/payments,/api/payments/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/