server:
  port: 8086

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:mysql://localhost:3306/smart_stadium?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 16082005
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB