# Cổng của Eureka Server (nên để 8761 hoặc giữ 8080 nếu bạn muốn)
server.port=8761

# Không tự đăng ký chính nó vào Eureka (vì nó chính là Server)
eureka.client.register-with-eureka=false

# Không tải registry về vì nó là nguồn cung cấp registry
eureka.client.fetch-registry=false